language: c

compiler:
  - gcc

sudo: required

dist: trusty

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y libgmp-dev gperf
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  - pip --version
  - sudo pip install cpp-coveralls
  
#tests
script:
  - ./.travis/build.sh

#   - coveralls -r . -b src --gcov-options '\-lp'
after_success:
  - lcov --directory build --base-directory src --capture --output-file coverage.info
  - coveralls-lcov coverage.info
