language: c

compiler:
  - gcc
  - clang

sudo: required

env:
  matrix:
    - BUILD_TYPE=debug 
      ENABLE_COVERAGE=OFF
    - BUILD_TYPE=release
      ENABLE_COVERAGE=OFF
    - BUILD_TYPE=gcov
      ENABLE_COVERAGE=ON
      
dist: trusty

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y libgmp-dev gperf
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

#tests
script:
  - ./.travis/build.sh

after_success:
  - if [[ $ENABLE_COVERAGE == ON ]]; then
      lcov --directory build --base-directory src --capture --output-file coverage.info
      coveralls-lcov coverage.info
    fi
