language: c

compiler:
  - gcc


# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install  -y libgmp-dev gperf
  - sudo apt-get install -y python-pip
  - pip --version
  - sudo pip install cpp-coveralls
  
#tests
script:
  - ./.travis/build.sh

after_success:
  - coveralls -b build/x86_64-unknown-linux-gnu-gcov/obj  -r src --gcov-options '\-lp';
